### ISSUE TITLE
Whenever one replicates the development setup in local an 'UnicodeEncodeError' occurs.

### ISSUE THREAD

**Issue by Abinash-bit** [OpenAstronomy/Universe_OA#92]
# Steps to replicate the issue.

## Step 1:

`git clone https://github.com/OpenAstronomy/Universe_OA.git`

## Step 2:

`cd Universe_OA`

## Step 3:

`pip install -r requirements.txt`

## Step 4:

`rm -rf .doit.db.* && rm -rf cache && nikola clean && nikola forget && rm -rf __pycache__ && rm -rf output
`

## Step 5:

`python grab.py`

## Issue Description:

`Traceback (most recent call last):
  File "C:\Users\user\Desktop\Universe_OA\grab.py", line 128, in <module>
    students_times[student] = grab_student(students_times[student],
  File "C:\Users\user\Desktop\Universe_OA\grab.py", line 101, in grab_student
    post.write(TEMPLATE.format(title=title_post,
  File "C:\Users\user\miniconda3\envs\aligner\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0393' in position 1193: character maps to <undefined>`

**Comment by Debarpan08** [comment]
Is this issue still open?
